const fs = require('fs');

const data = fs.readFileSync('public/face.obj', 'utf-8');
const lines = data.split('\n');

const vertices = [];
const faceIndices = [];

let minX = Infinity, maxX = -Infinity;
let minY = Infinity, maxY = -Infinity;
let minZ = Infinity, maxZ = -Infinity;

for (let line of lines) {
  if (line.startsWith('v ')) {
    const parts = line.trim().split(/\s+/);
    if (parts.length >= 4) {
      const x = parseFloat(parts[1]);
      const y = parseFloat(parts[2]);
      const z = parseFloat(parts[3]);
      vertices.push([x, y, z]);
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
      if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
    }
  } else if (line.startsWith('f ')) {
    const parts = line.trim().split(/\s+/);
    const fIdx = [];
    for (let i = 1; i < parts.length; i++) {
      const vIndex = parseInt(parts[i].split('/')[0], 10) - 1;
      fIdx.push(vIndex);
    }
    // Triangulate
    for (let i = 1; i < fIdx.length - 1; i++) {
      faceIndices.push([fIdx[0], fIdx[i], fIdx[i + 1]]);
    }
  }
}

// Center and scale to [-1, 1]
const cx = (minX + maxX) / 2;
const cy = (minY + maxY) / 2;
const cz = (minZ + maxZ) / 2;
const maxSpan = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
const scale = 2.0 / maxSpan;

const flatVertices = [];
for (let v of vertices) {
  flatVertices.push(
    (v[0] - cx) * scale,
    (v[1] - cy) * scale,
    (v[2] - cz) * scale
  );
}

// Extract unique edges
const edgeMap = new Map();
for (let f of faceIndices) {
  const edges = [
    [f[0], f[1]],
    [f[1], f[2]],
    [f[2], f[0]]
  ];
  for (let e of edges) {
    const min = Math.min(e[0], e[1]);
    const max = Math.max(e[0], e[1]);
    edgeMap.set(`${min}_${max}`, [min, max]);
  }
}

const allEdges = Array.from(edgeMap.values());

// Curate subset of connections to avoid solid wireframe clutter
// We want ~30% of edges randomly distributed, but maybe keep more edges near the eyes/face center for definition.
const curatedEdges = [];
for (let e of allEdges) {
  const v1 = vertices[e[0]];
  const v2 = vertices[e[1]];
  
  // Center is roughly x=0, y=cy+something.
  // We want higher density around eyes and nose.
  // Normalized Y center is roughly 0.1, X is 0.
  const nx1 = (v1[0] - cx) * scale;
  const ny1 = (v1[1] - cy) * scale;
  const distToCenter = Math.sqrt(nx1 * nx1 + (ny1 - 0.1) * (ny1 - 0.1));
  
  // Base probability
  let prob = 0.25; 
  if (distToCenter < 0.3) {
    prob = 0.6; // 60% of edges near eyes/nose
  } else if (distToCenter < 0.6) {
    prob = 0.4;
  }
  
  if (Math.random() < prob) {
    curatedEdges.push(e[0], e[1]);
  }
}

const pointSet = new Set(curatedEdges);

const outContent = `// Auto-generated by parseFace.cjs
export const faceVertices = new Float32Array([${flatVertices.map(n => n.toFixed(4)).join(',')}]);
export const faceLines = new Uint32Array([${curatedEdges.join(',')}]);
export const facePoints = new Uint32Array([${Array.from(pointSet).join(',')}]);
`;

fs.writeFileSync('src/components/3d/faceVertices.ts', outContent);
console.log('Generated faceVertices.ts with', flatVertices.length / 3, 'vertices,', curatedEdges.length / 2, 'lines, and', pointSet.size, 'points.');
