const fs = require('fs');

const data = fs.readFileSync('public/face.obj', 'utf-8');
const lines = data.split('\n');

const vertices = [];
let minX = Infinity, maxX = -Infinity;
let minY = Infinity, maxY = -Infinity;
let minZ = Infinity, maxZ = -Infinity;

for (let line of lines) {
  if (line.startsWith('v ')) {
    const parts = line.split(/\s+/);
    if (parts.length >= 4) {
      const x = parseFloat(parts[1]);
      const y = parseFloat(parts[2]);
      const z = parseFloat(parts[3]);
      vertices.push([x, y, z]);
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
      if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
    }
  }
}

// Center and scale to [-1, 1]
const cx = (minX + maxX) / 2;
const cy = (minY + maxY) / 2;
const cz = (minZ + maxZ) / 2;
const maxSpan = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
const scale = 2.0 / maxSpan;

const normalized = vertices.map(v => [
  (v[0] - cx) * scale,
  (v[1] - cy) * scale,
  (v[2] - cz) * scale
]);

// Filter out internal points slightly to improve silhouette (very basic heuristic)
// Points with higher Z are on the surface
const skullCount = 6000;
const skullPoints = [];
for (let i = 0; i < skullCount; i++) {
  const base = normalized[i % normalized.length];
  skullPoints.push(base[0], base[1], base[2]);
}

// Structured Eyes
const eyeLeftCenter = [-0.18, 0.12, 0.45];
const eyeRightCenter = [0.18, 0.12, 0.45];

const eyePoints = [];
const eyeTypes = []; // 0.0 = Iris, 1.0 = Orbit

const createEye = (center) => {
  // Layer 2: Cyan Iris Ring (dense)
  const irisCount = 400;
  const irisRadius = 0.05;
  for (let i = 0; i < irisCount; i++) {
    const theta = (i / irisCount) * Math.PI * 2;
    // Add slight noise to ring
    const r = irisRadius + (Math.random() - 0.5) * 0.005;
    const x = center[0] + r * Math.cos(theta);
    const y = center[1] + r * Math.sin(theta);
    const z = center[2] + (Math.random() - 0.5) * 0.01;
    eyePoints.push(x, y, z);
    eyeTypes.push(0.0);
  }

  // Layer 3: Neural Orbit (loose, scattered further out)
  const orbitCount = 600;
  const orbitRadiusMin = 0.06;
  const orbitRadiusMax = 0.12;
  for (let i = 0; i < orbitCount; i++) {
    const theta = Math.random() * Math.PI * 2;
    const r = orbitRadiusMin + Math.random() * (orbitRadiusMax - orbitRadiusMin);
    const x = center[0] + r * Math.cos(theta);
    const y = center[1] + r * Math.sin(theta);
    const z = center[2] + (Math.random() - 0.5) * 0.04 - (r - orbitRadiusMin) * 0.2; // Curve back into socket
    eyePoints.push(x, y, z);
    eyeTypes.push(1.0);
  }
};

createEye(eyeLeftCenter);
createEye(eyeRightCenter);

const outContent = `// Auto-generated by parseFace.cjs
export const skullPoints = new Float32Array([${skullPoints.map(n => n.toFixed(4)).join(',')}]);
export const eyePoints = new Float32Array([${eyePoints.map(n => n.toFixed(4)).join(',')}]);
export const eyeTypes = new Float32Array([${eyeTypes.map(n => n.toFixed(1)).join(',')}]);
`;

fs.writeFileSync('src/components/3d/faceVertices.ts', outContent);
console.log('Generated src/components/3d/faceVertices.ts');
