const fs = require('fs');

const data = fs.readFileSync('public/face.obj', 'utf-8');
const lines = data.split('\n');

const vertices = [];
let minX = Infinity, maxX = -Infinity;
let minY = Infinity, maxY = -Infinity;
let minZ = Infinity, maxZ = -Infinity;

for (let line of lines) {
  if (line.startsWith('v ')) {
    const parts = line.split(/\s+/);
    if (parts.length >= 4) {
      const x = parseFloat(parts[1]);
      const y = parseFloat(parts[2]);
      const z = parseFloat(parts[3]);
      vertices.push([x, y, z]);
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
      if (z < minZ) minZ = z; if (z > maxZ) maxZ = z;
    }
  }
}

// Center and scale to [-1, 1]
const cx = (minX + maxX) / 2;
const cy = (minY + maxY) / 2;
const cz = (minZ + maxZ) / 2;
const maxSpan = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
const scale = 2.0 / maxSpan;

const normalized = vertices.map(v => [
  (v[0] - cx) * scale,
  (v[1] - cy) * scale,
  (v[2] - cz) * scale
]);

// Resample or duplicate vertices to hit exactly 9000 for skull
const skullCount = 9000;
const skullPoints = [];
for (let i = 0; i < skullCount; i++) {
  // Use a base point
  const base = normalized[i % normalized.length];
  // Add slight noise if duplicating
  const noise = i >= normalized.length ? (Math.random() - 0.5) * 0.01 : 0;
  skullPoints.push(base[0] + noise, base[1] + noise, base[2] + noise);
}

// Eyes: procedurally generated dense clusters
// Based on typical face anatomy: eyes are a bit above the center, spread horizontally, and towards the front
const eyeLeftCenter = [-0.25, 0.1, 0.45];
const eyeRightCenter = [0.25, 0.1, 0.45];
const eyeRadius = 0.08;

const eyeCount = 3000;
const eyePoints = [];
for (let i = 0; i < eyeCount; i++) {
  const isLeft = i < eyeCount / 2;
  const center = isLeft ? eyeLeftCenter : eyeRightCenter;
  
  // Create dense sphere/disc distribution
  const u = Math.random();
  const v = Math.random();
  const theta = u * 2.0 * Math.PI;
  const phi = Math.acos(2.0 * v - 1.0);
  const r = eyeRadius * Math.cbrt(Math.random()); // Volume distribution
  
  const x = center[0] + r * Math.sin(phi) * Math.cos(theta);
  const y = center[1] + r * Math.sin(phi) * Math.sin(theta);
  let z = center[2] + r * Math.cos(phi);
  
  // Flatten slightly into a disc, pointing forward
  z = center[2] + (z - center[2]) * 0.3;
  
  eyePoints.push(x, y, z);
}

const outContent = `// Auto-generated by parseFace.cjs
export const skullPoints = new Float32Array([${skullPoints.map(n => n.toFixed(4)).join(',')}]);
export const eyePoints = new Float32Array([${eyePoints.map(n => n.toFixed(4)).join(',')}]);
`;

fs.writeFileSync('src/components/3d/faceVertices.ts', outContent);
console.log('Generated src/components/3d/faceVertices.ts');
