// Procedurally generated face vertex positions
// Each point is [x, y, z] representing a position on a human face silhouette
// Generated by sampling a parametric face model

function buildFaceVertices(): Float32Array {
  const points: number[] = []

  const push = (x: number, y: number, z: number, jitter = 0.05) => {
    points.push(
      x + (Math.random() - 0.5) * jitter,
      y + (Math.random() - 0.5) * jitter,
      z + (Math.random() - 0.5) * jitter
    )
  }

  // --- Skull dome ---
  for (let i = 0; i < 200; i++) {
    const phi = Math.random() * Math.PI * 0.5
    const theta = Math.random() * Math.PI * 2
    const r = 1.1 + Math.random() * 0.04
    push(r * Math.sin(phi) * Math.cos(theta), 0.4 + r * Math.cos(phi) * 0.7, -0.1 + r * Math.sin(phi) * Math.sin(theta) * 0.5, 0.02)
  }

  // --- Forehead ---
  for (let i = 0; i < 160; i++) {
    const x = (Math.random() - 0.5) * 1.4
    const y = 0.7 + Math.random() * 0.5
    const z = Math.sqrt(Math.max(0, 1 - x * x * 0.5)) * 0.35
    push(x, y, z)
  }

  // --- Brow ridge ---
  for (let side = -1; side <= 1; side += 2) {
    for (let i = 0; i < 60; i++) {
      const t = i / 60
      const x = side * (0.25 + t * 0.38)
      const y = 0.45 + Math.sin(t * Math.PI) * 0.08
      const z = 0.45 - t * 0.06
      push(x, y, z, 0.035)
    }
  }

  // --- Eye sockets (dark recessed area) ---
  for (let side = -1; side <= 1; side += 2) {
    const cx = side * 0.38
    for (let i = 0; i < 120; i++) {
      const angle = Math.random() * Math.PI * 2
      const r = Math.random() * 0.18
      push(cx + r * Math.cos(angle) * 1.2, 0.22 + r * Math.sin(angle) * 0.7, 0.3 - r * 0.6, 0.025)
    }
    // Eyelid upper arc
    for (let i = 0; i < 50; i++) {
      const t = (i / 50) * Math.PI
      push(cx + Math.cos(t) * 0.2, 0.28 + Math.sin(t) * 0.08, 0.38, 0.02)
    }
    // Eyelid lower arc
    for (let i = 0; i < 30; i++) {
      const t = (i / 30) * Math.PI
      push(cx + Math.cos(t) * 0.18, 0.18 - Math.sin(t) * 0.04, 0.37, 0.02)
    }
    // Iris / pupil cluster
    for (let i = 0; i < 80; i++) {
      const r = Math.random() * 0.09
      const a = Math.random() * Math.PI * 2
      push(cx + r * Math.cos(a), 0.23 + r * Math.sin(a) * 0.8, 0.41, 0.01)
    }
  }

  // --- Nose bridge ---
  for (let i = 0; i < 80; i++) {
    const t = i / 80
    const x = (Math.random() - 0.5) * 0.14
    const y = 0.18 - t * 0.38
    const z = 0.42 + t * 0.18
    push(x, y, z, 0.025)
  }
  // Nose tip & wings
  for (let i = 0; i < 100; i++) {
    const angle = Math.random() * Math.PI * 2
    const r = Math.random() * 0.15
    push(r * Math.cos(angle) * 1.4, -0.22 + r * Math.sin(angle) * 0.6, 0.58 - r * 0.2, 0.02)
  }
  // Nostrils
  for (let side = -1; side <= 1; side += 2) {
    for (let i = 0; i < 30; i++) {
      push(side * 0.12 + (Math.random() - 0.5) * 0.07, -0.25 + (Math.random() - 0.5) * 0.05, 0.56, 0.015)
    }
  }

  // --- Cheekbones ---
  for (let side = -1; side <= 1; side += 2) {
    for (let i = 0; i < 100; i++) {
      const t = i / 100
      const x = side * (0.55 + t * 0.15)
      const y = 0.05 - t * 0.25
      const z = 0.28 - t * 0.08
      push(x, y, z, 0.04)
    }
  }

  // --- Upper lip ---
  for (let i = 0; i < 80; i++) {
    const t = (i / 80) * Math.PI * 2
    const x = Math.sin(t) * 0.22
    const y = -0.38 + Math.abs(Math.sin(t * 2)) * 0.03
    const z = 0.5 + Math.cos(t * 0.5) * 0.03
    push(x, y, z, 0.018)
  }
  // --- Lower lip ---
  for (let i = 0; i < 60; i++) {
    const t = (i / 60) * Math.PI
    push(Math.sin(t) * 0.2, -0.44 - Math.sin(t) * 0.04, 0.52, 0.018)
  }
  // Mouth corners
  for (let side = -1; side <= 1; side += 2) {
    for (let i = 0; i < 20; i++) {
      push(side * 0.22 + (Math.random() - 0.5) * 0.04, -0.4 + (Math.random() - 0.5) * 0.04, 0.49, 0.01)
    }
  }

  // --- Jaw / Chin ---
  for (let i = 0; i < 160; i++) {
    const t = (i / 160) * Math.PI
    const x = Math.sin(t) * (0.7 - Math.sin(t) * 0.15)
    const y = -0.6 - Math.sin(t * 0.5) * 0.35
    const z = 0.1 + Math.sin(t) * 0.2
    push(x, y, z, 0.04)
  }
  // Chin point cluster
  for (let i = 0; i < 40; i++) {
    push((Math.random() - 0.5) * 0.18, -0.92 + Math.random() * 0.05, 0.25, 0.02)
  }

  // --- Ears ---
  for (let side = -1; side <= 1; side += 2) {
    for (let i = 0; i < 80; i++) {
      const angle = Math.random() * Math.PI * 2
      const r = Math.random() * 0.14
      push(side * 0.85 + r * Math.cos(angle) * 0.4, 0.05 + r * Math.sin(angle), -0.1, 0.02)
    }
  }

  // --- Face skin fill (sparse) ---
  for (let i = 0; i < 400; i++) {
    const x = (Math.random() - 0.5) * 1.6
    const y = -0.9 + Math.random() * 1.9
    const rx = x / 0.8
    const ry = (y - 0.1) / 1.0
    if (rx * rx + ry * ry < 1.0) {
      const z = Math.sqrt(Math.max(0, 1 - rx * rx * 0.4 - ry * ry * 0.3)) * 0.45
      push(x, y, z, 0.03)
    }
  }

  // --- Neural scatter (background nodes around face) ---
  for (let i = 0; i < 300; i++) {
    const x = (Math.random() - 0.5) * 3.5
    const y = (Math.random() - 0.5) * 3.0
    const z = -0.6 + Math.random() * 0.4
    push(x, y, z, 0.08)
  }

  return new Float32Array(points)
}

// Build once and export as singleton
export const FACE_VERTICES = buildFaceVertices()
export const PARTICLE_COUNT = FACE_VERTICES.length / 3
